apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-prog
spec:
  replicas: 5
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels: 
      app: cpp-prog
  template:
    metadata:
      labels:
        app: cpp-prog
    spec:
      containers:
      - name: cpp-prog-docker
        image: ghcr.io/emilk92/cpp-prog-docker:latest
        ports:
          - name: custom-program
            containerPort: 3000
            protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
