name: C/C++ CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: make and package artifacts
      run: |
        make
        mkdir artifacts
        mv cpp-prog artifacts/
    - name: build docker image
      run: docker build --tag ghcr.io/emilk92/cpp-prog-docker:${GITHUB_RUN_ID}
    - name: login to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: push image
      run: docker push ghcr.io/emilk92/cpp-prog-docker:latest
