name: C/C++ CI

env:
  CPP_PROG_IMAGE_TAG: 1.0

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: make and package artifacts
      run: |
        make
        mkdir artifacts
        mv cpp-prog artifacts/
    - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
    - name: build docker image
      run: docker build -t cpp-prog-docker:latest .
    - name: tag docker image
      run: docker tag cpp-prog-docker:latest ghcr.io/emilk92/cpp-prog-docker:$CPP_PROG_IMAGE_TAG
    - name: login to package registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    - name: push docker image to registry
      run: docker push "ghcr.io/emilk92/cpp-prog-docker:$CPP_PROG_IMAGE_TAG"
