name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: debian-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: package artifacts
      run: |
        mkdir artifacts
        cp cpp-prog artifacts/
  publish:
    needs: build
    runs-on: debian-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: cpp-prog-docker
          labels: ${{ steps.meta.outputs.labels }}
