name: C/C++ CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: package artifacts
      run: |
        mkdir artifacts
        cp cpp-prog artifacts/
    - name: Login to Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io/emilk92
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ github.actor }}/cpp-prog-docker:latest
