name: C/C++ CI

env:
  CPP_PROG_IMAGE_TAG: "1.1.14"

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: make and package artifacts
      run: |
        make
        mkdir artifacts
        mv cpp-prog artifacts/
    - name: build docker image
      run: docker build -t cpp-prog-docker:$CPP_PROG_IMAGE_TAG -t cpp-prog-docker:latest .
    - name: tag docker image
      run: | 
        docker tag cpp-prog-docker:latest ghcr.io/emilk92/cpp-prog-docker:latest
        docker tag cpp-prog-docker:latest ghcr.io/emilk92/cpp-prog-docker:$CPP_PROG_IMAGE_TAG
    - name: login to package registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    - name: push docker image to registry
      run: docker push --all-tags ghcr.io/emilk92/cpp-prog-docker
