name: C/C++ CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: make and package artifacts
      run: |
        make
        mkdir artifacts
        mv cpp-prog artifacts/
    - name: build docker image
      uses: flownative/action-docker-build@v1
      with:
        tag_ref: ${{ github.ref }}
        image_name: cpp-prog-docker
        registry_password: ${{ secrets.GITHUB_TOKEN }}
    - name: push docker image to registry
      run: docker push "ghcr.io/emilk92/cpp-prog-docker:latest"
