name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: package artifacts
      run: |
        mkdir artifacts
        cp cpp-prog artifacts/
    - name: publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cpp-prog
        path: artifacts/cpp-prog

